# Generated by Django 4.2 on 2023-05-01 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tip_obr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mask', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Obr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(max_length=255, unique=True)),
                ('note', models.CharField(max_length=255)),
                ('tip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drfsite.tip_obr')),
            ],
            options={
                'unique_together': {('sn', 'tip')},
            },
        ),
    ]
