# Generated by Django 4.2 on 2023-05-01 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drfsite', '0002_rename_obr_equipment_rename_tip_obr_equipmenttype_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='type',
            new_name='equipment_type_id',
        ),
        migrations.RenameField(
            model_name='equipment',
            old_name='sn',
            new_name='serial_number',
        ),
        migrations.AlterUniqueTogether(
            name='equipment',
            unique_together={('serial_number', 'equipment_type_id')},
        ),
    ]
